### ISSUE TITLE
After Burner Climax crashes after "SYSTEM STARTUP"

### ISSUE THREAD

**Issue by antoniodesousa** [teknogods/TeknoParrotUI#596] opened 2023-12-14 14:40 UTC
Sadly, this game doesn't work even after the recent 23.12.1 AMD driver update. I can access the test menu without issues though. And I'm pretty sure is a good dump because it does work on the old 22.5.2 driver.

The game boots this screen and after a minute it just closes again:

![001](https://github.com/teknogods/TeknoParrotUI/assets/10920974/50b73559-6236-4cf0-bc32-cfdc54bc2ff3)

I read somewhere that @Nezarn is working in a new fix for this game.
I hope that the game starts working again when the new fix is released.

**Comment by Nezarn** [comment] 2023-12-14 15:43
Duplicate of https://github.com/teknogods/TeknoParrotUI/issues/518

**Closed by Nezarn** 2023-12-14 15:43 UTC
