### ISSUE TITLE
Control issues when played with --startMinimized enabled

### ISSUE THREAD

**Issue by PolybiusExtreme** [teknogods/TeknoParrotUI#758] opened 2024-05-10 15:30 UTC
The following games have control issues when playing with --startMinimized enabled

After Burner Climax - no controls work
Lets Go Jungle & Lets Go Jungle Special - gun movement stutters

**Comment by EmiMidnight** [comment] 2024-05-11 01:17
I can't reproduce it, both the elfldr1 and elfldr2 versions of ABC seem to work just fine using startMinimized. (Tried both xinput and dinput)

What windows version are you two on?
Desktop or Laptop? 
I think it might be related to windows 11 (and maybe 10) where it can throttle background processes. Because TPUI is responsible for all the IO, if thats throttled you would get these kinds of issues.

**Comment by nixxou** [comment] 2024-05-11 06:58
I use Windows 11, yes. Amd gpu if that matter.
If i start .\TeknoParrotUi.exe --startMinimized --profile="C:\teknoparrot\UserProfiles\abc.xml"
I will not get any inputs.
If i use .\TeknoParrotUi.exe --profile="C:\teknoparrot\UserProfiles\abc.xml" it's working.

**Comment by PolybiusExtreme** [comment] 2024-05-11 07:03
I am on Win 11 with an Nvidia 3070.
@nixxou you dont have to write the path to the profile, it should work just with „profile=abc.xml“

**Comment by nixxou** [comment] 2024-05-11 09:07
I prefer to use the full path It's just personal preference and convenience.

**Comment by EmiMidnight** [comment] 2024-05-18 11:12
A bit of a late response, but it might be worth playing around with some of the workarounds mentioned here, as I think it's a case of windows throttling background processes. (aka TPUI when it is running minimized)

https://www.tenforums.com/tutorials/99445-how-enable-disable-power-throttling-windows-10-a.html

**Comment by PolybiusExtreme** [comment] 2024-05-19 11:07
Thank you @EmiMidnight for your response. I tried it with power throttling disabled but that changed nothing, no controls with --startMinimized enabled.

**Comment by EmiMidnight** [comment] 2024-10-12 15:08
Hiho. I just pushed a new update that might actually resolve this. Once its out in a few minutes, it would be great if people could test it and let me know. 
(I was finally able to reliably reproduce it on my machine, and the new fix did fix it for me.)

**Comment by nixxou** [comment] 2024-10-12 15:34
It works now. Thanks a lot.
If that would be possible to also minimize the console windows of BudgieLoader/OpenLoader, it would be nice too. Eventually with an other command line arguments. And if that's not possible, just a CreateNoWindow option would be nice). Lot of people with frontend don't want stuff popup over their art when launching a game.

**Comment by EmiMidnight** [comment] 2024-10-12 16:25
Closing this as the original issue is resolved now. For the window stuff, I just pushed another update so Budgieloader should also be hidden, as long as Hide Console Windows is enabled in TPUI, as mentioned it on discord. :)

**Closed by EmiMidnight** 2024-10-12 16:25 UTC
