### ISSUE TITLE
Hot Wheels controls

### ISSUE THREAD

**Issue by Retrokrell** [teknogods/TeknoParrotUI#537] opened 2023-09-14 23:49 UTC
Hot Wheels, car is stuck in it's lane.  Turning left or right rotates the car, but doesn't change lanes. Gas pedal/button does nothing. For both joysticks or wheel.

**Comment by EmiMidnight** [comment] 2023-09-15 05:43
Did you install the controlsfix from the #fixes channel in the discord?

**Comment by EmiMidnight** [comment] 2023-09-19 14:14
Can confirm over here. Will have to investigate.

**Comment by cor094** [comment] 2023-09-19 15:18
I think the pedal issue is caused by needing to calibrate in the test menu. I hadn't heard of the lane changing issue, so I tested as well. Loaded the game on my older build. It worked great. Updated TP, now had the lane changing issue as described. Interestingly enough, when I went back to the old TP build, it now had the same lane-changing issue. In order to fix, I deleted the hotwheels folder in User\AppData\LocalLow\Sarbakan\ - then went back to test menu and re-calibrated pedals. Now, it functions normally again in my old TP build.

On a side note - another issue with this game is all of the debug keys. Theres a box in TP UI to disable them, but doesn't work, making it hard to play on an ipac or other keyboard device. https://github.com/teknogods/teknoparrot-issues/issues/193

**Comment by EmiMidnight** [comment] 2023-09-19 23:05
Recalibrating seems to have worked for me. I wonder why it's neccessary all of a sudden though.

**Comment by Retrokrell** [comment] 2023-09-20 00:56
That fixed the gas pedal problem.  But it's still not changing lanes.  I also noticed that the wheel calibration says Left: 0, Center: 127, Right:254.  Think that has something to do with it?  My Logitech driver is set to 270 rotation and works fine for everything else.

**Comment by Joejoe55** [comment] 2023-09-21 03:36
Like the messages above, I tested and can press gas , the car turns or pivots, but doesn't change lanes, tested with latest TP , done calibration aswell as have the v2 fix, also had tried just before update and was same thing, so unsure when it started, tried x-input aswell as d-input

**Comment by Retrokrell** [comment] 2023-09-21 13:14
What were your wheel settings in the test menu compared to mine?

**Comment by Retrokrell** [comment] 2023-10-15 16:10
Just curious if any more work has been done on this one?  Thanks.

**Comment by nanometrovovo2** [comment] 2023-11-11 18:08
Same issue here,  I tried with clean dump and deleting User\AppData\LocalLow\Sarbakan\ and calibration in test menu with p3 controls. Same issue, in last TP update, the cars only rotate with the wheel

**Comment by Dankfambo25** [comment] 2023-11-15 09:22
yeah no luck here, still having issues

**Comment by EmiMidnight** [comment] 2023-11-26 09:10
Just pushed an update to TPCore, could any of you try it and see if that fixes it for you? It should.

**Comment by Retrokrell** [comment] 2023-11-26 18:17
THANK YOU VERY MUCH!  This is working again!  So glad you found the time to address this older issue.  Hope it was something simple.

**Comment by EmiMidnight** [comment] 2023-11-26 18:27
I've tried a couple of times to fix this in the past few weeks but I thought it was IO/Controls related. It wasn't haha, seems like it might be a last minute piracy check possibly. Only finally figured it out because of Booms. Gonna close this issue and mark it as solved then.

**Closed by EmiMidnight** 2023-11-26 18:27 UTC
