### ISSUE TITLE
Virtua Fighter 5r

### ISSUE THREAD

**Issue by unionjac13** [teknogods/TeknoParrotUI#824] opened 2024-07-15 21:09 UTC
I played this a while back and retested the other day here are my findings:
So to get this game, you have to go all the way to the final stage. Before that, no major issue it works fine. But on the final stage, the rendering is not working correctly. If you move it get message VIrtua5r Final Stage rendering bug. See what you can do 
Thanks for all your hard work

**Comment by nixxou** [comment] 2024-07-15 22:11
Duplicate of https://github.com/teknogods/TeknoParrotUI/issues/779

**Closed** 2024-07-25 11:35 UTC
